appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: PS3ATp0VOTH5QijidD8ovvW2bBE0J/QjrBwERMcMBSnIC4yyM32tQfpfngqRn2sI8nq4IX7HNgDYThmwZq5xEoIpDb/C8AvAwsbH7I0jK+DU37sUZEihtA2zNPB6EmYh3ypa8eMjr6Tf/KSS7qkuW1XsBYQnpttrzueelKKQkNHjDAV5a/bx0vxvXpnVBBfIOtKxs3+cYEA1J+WtafM1xwmd+JHNhdUKC6h6WbsbKdfbYEjIPE2hdalEn8b6+HqMI7IjGWiOAR75bJdq1JWTR/mkSbv34H8fPCUR17gSlNVqBlnmEEvQmC++AYCaG82CYOdhYA4Ybc1BupLOLVGsPX7n+ufL4XWafuTARZJAXmA4YLpOlSr7uHNhJ4XLembauGtY0IUrGThKPG89zXCXrac/sU94rdXXHkN2g0TBGutK0yuiXIIFXjhV6yL4UB67OujjVs4xUrrL5cIyacTfl+AVU0qGbo0N5b2MpKutrhew5FGCgwS3UzHAHHhtypsklCDtNTdLqsk+gX3ifUTnLWOCEvuoDSfwuFDlp91xbQIElOSrFKeVZ1MCWE4YNjULWXwu2/Oij9gQWOmQwGlhF5C3MjSZ7HU36PS8A9qfu3z4+Aq9GghytXYa+dIgOLyoCQyptzOTZb2KXa/fHa8l743KpaX623+VVxKivJOA/rs=}
